// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcgz4S5hQb37PWl9py6srT_k7-XasxHaE',
    appId: '1:942814661449:web:4153da448fb443f4d32898',
    messagingSenderId: '942814661449',
    projectId: 't2024cs3-univents',
    authDomain: 't2024cs3-univents.firebaseapp.com',
    databaseURL: 'https://t2024cs3-univents-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 't2024cs3-univents.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU1EPqoxyC6ixlWuabrLfAAYTWyrEyvE0',
    appId: '1:942814661449:android:278eaba064e5f47ad32898',
    messagingSenderId: '942814661449',
    projectId: 't2024cs3-univents',
    databaseURL: 'https://t2024cs3-univents-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 't2024cs3-univents.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSj-u4RthuDa9mpk3dczdh7fhyPlN92KE',
    appId: '1:942814661449:ios:aa8804861116472bd32898',
    messagingSenderId: '942814661449',
    projectId: 't2024cs3-univents',
    databaseURL: 'https://t2024cs3-univents-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 't2024cs3-univents.firebasestorage.app',
    iosClientId: '942814661449-nie5cv9trnqfimkqs5jsd01budeen7la.apps.googleusercontent.com',
    iosBundleId: 'com.example.univents',
  );

}